name: 'Permasigner'
description: 'Permanently sign an IPA and generate a deb, useful for CI/CD'
author: 'Nebula'

inputs:
  input:
    description: 'Path to an IPA to permasign'
    required: true
  output:
    description: 'Output directory of the deb file'
    required: false
    default: ${GITHUB_WORKSPACE}/permasigner-out
  source:
    description: 'Run from source instead of package'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Set up Procursus
      if: runner.os == 'macOS'
      uses: beerpiss/procursus-action@v1
      with:
        packages: ldid python3 git
        cache: true
        mirror: 'https://procursus.itsnebula.net/'
        
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt install git python3 python3-pip
    
    - name: Install Permasigner
      shell: bash
      run: |
        if [ "${{ inputs.source }}" == "true" ]; then
            python3 -m pip install -U git+https://github.com/permasigner/permasigner
        else
            python3 -m pip install permasigner
        fi
        
        python3 -m permasigner -p ${{ inputs.input }} -o ${{ inputs.output }} -d

branding:
  icon: pen
  color: purple
