name: Tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  test-source:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download test IPA
        run: |
          wget -nc -O ${{ github.workspace }}/Taurine.ipa https://github.com/Odyssey-Team/Taurine/releases/download/1.1.6/Taurine-1.1.6.ipa
      - name: Run Github action
        uses: permasigner/action@main
        with:
          input: "${{ github.workspace }}/Taurine.ipa"
          source: true
      - name: Upload permasigned test IPA
        uses: actions/upload-artifact@v3
        with:
          name: test-source-${{ matrix.os }}
          path: ${{ github.workspace }}/permasigner-out/*
